### ISSUE TITLE
clear(id) or clearAll() is not working

### ISSUE THREAD

**Issue by ahunter135** [katzer/cordova-plugin-local-notifications#1342]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.
I am trying to use the clear or clearAll method for a local notification and it does not work. At all.
## Your Environment

* Plugin version: Latest
* Platform: Android
* OS version: Latest
* Device manufacturer / model: Google Pixel XL
* Cordova version (```cordova -v```): 7.0.1
* Cordova platform version (```cordova platform ls```): android 6.2.3
  ios 4.4.0
* Plugin config
* Ionic Version (if using Ionic) 2.2.1

## Expected Behavior

_Tell us what should happen_
The notification that is scheduled should be removed.
## Actual Behavior
Nothing is happening and notification still goes off.
_Tell us what happens instead_

## Steps to Reproduce

_Reproduce this issue; include code to reproduce, if relevant_

  1. ... Schedule a notification using: $cordovaLocalNotification.schedule({
            id: 1,
            title: 'Journal Time',
            text: 'Dont Forget to Journal Today!',
            icon: "file://resources/icon.png",
            sound: "file://resources/sound.mp3",
            at: _10SecondsFromNow
          }).then(function(result) {
            // ...
  2. ...Try to clear it. using: $cordovaLocalNotification.cancel(1).then(function(result) {
            // ...
          });

## Context

_What were you trying to do?_

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by luka5** [comment]
Today I had a similar issue. I was not able to close the first notification with a click, swipe or clearAll. However each notification with id > 1 worked.
Another plugin of the same app was already showing a notification and the new notification with id 1 just updated the existing one.
However, it was still set to ongoing and clearAll was not working.
I fixed it by starting with id 2, since the other plugin seems to use id 1.

This occured in combination with "cordova-plugin-mauron85-background-geolocation"

Do you also have another notification visible, which gets updated by your code?

**Comment by marcovtwout** [comment]
The notification has to be canceled or cleared depending on if it repeats and if it was already triggered.

Maybe this bit of plugin internals will be helpful in understanding which function to call: https://github.com/katzer/cordova-plugin-local-notifications/blob/251a7ccfe30e1ade538fe4493a734c3d465647dc/src/android/notification/Notification.java#L186-L217

**Comment by marcovtwout** [comment]
Also see https://github.com/katzer/cordova-plugin-local-notifications/wiki/06.-Clear and https://github.com/katzer/cordova-plugin-local-notifications/wiki/07.-Cancelation

**Comment by katzer** [comment]
Please retry with latest code and raise again if not solved.
